[package]
name = "offline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
idpf = { path = "./../libidpf"}
bincode = { version = "1.3"}